name: Validate and Auto Publish

on:
  push:
    paths: index.html
    branches:
      - main
  pull_request: {}

jobs:
  validate-and-publish:
    name: Validate and Publish
    runs-on: ubuntu-latest # only linux supported at present
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2 # use the action

